### ISSUE TITLE
Build logs are not displayed during cf-push

### ISSUE THREAD

**Issue by Syerram** [cloudfoundry/cf-k8s-logging#18]
## Expected Behavior
During app staging, I expect cf-push to stream build logs.

## Actual Behavior
No build logs are shown to the user.

## Steps to Reproduce the Problem
- Run through steps in cf-for-k8s install steps
- Run `cf push app -p /path/to/java-app`
- Notice the lack of build logs

## Additional information
See this [slack thread](https://cloudfoundry.slack.com/archives/CH9LF6V1P/p1584638456029000) for more information.

**Comment by pianohacker** [comment]
Per our discussion with CAPI, the fix is to put a tag on the build pods that we can grab the correct source type from.

**Comment by pianohacker** [comment]
Fixed by PR #23 .
