### ISSUE TITLE
Migrate DaemonSets from extensions/v1beta1 to apps/v1

### ISSUE THREAD

**Issue by pivotaljohn** [cloudfoundry/cf-k8s-logging#2]
Kubernetes 1.16 removed the `extensions/v1beta1` API group.  https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

`config/manifests/500-fluentd-daemonset.yaml` includes a resource definition from that API group.

Please migrate that resource definition to meet the `apps/v1` specification.

Note that `apps/v1/DaemonSet` requires that `spec.selector` needs to be a subset matching `spec.template.metadata.labels`.

This came to CF for K8s / Release Integration's attention through: cloudfoundry/cf-for-k8s#22.

**Comment by vitreuz** [comment]
Hey, Relint Team here,

Please let us know what your plan is here.

Also, what slack channel should we use to contact the cf-k8s-logging group?

FWIW Julian has added additional context here https://github.com/cloudfoundry/cf-for-k8s/issues/22#issuecomment-587597269.

**Comment by MasslessParticle** [comment]
Merged this change: https://github.com/cloudfoundry/cf-k8s-logging/pull/11
