### ISSUE TITLE
If instance index is not a string, conversion into syslog fails

### ISSUE THREAD

**Issue by MasslessParticle** [cloudfoundry/cf-k8s-logging#27]
CAPI team recently used the Fluent Logging Ruby to send their logs to the Forwarder API. The team was  sending logs in the correct format, but the `instance_id` was 0. This caused parsing errors in the output plugin that eventually showed up as parse errors in log cache.

**Comment by cwlbraa** [comment]
I'm actually kinda curious what fills instance id on the in-the-app-container log side... is it `CF_INSTANCE_INDEX`?

**Comment by heycait** [comment]
Closing this as there seems to be a workaround applied
