### ISSUE TITLE
Log Cache should allow operators to set a fixed memory limit

### ISSUE THREAD

**Issue by KesavanKing** [cloudfoundry/cf-k8s-logging#36]
We did a scalability tests on cf-for-k8s version [0.6.0](https://github.com/cloudfoundry/cf-for-k8s/releases/tag/v0.6.0). We were succeeded in deploying 1600 apps. To simulate real workload scenario we deploy apps which generate 1 log/sec and 1 req/sec.  During the tests we could observe log-cache consumes > 10Gi of memory . We tried by scaling to two replicas, even with that it memory spikes up. 

Below graph show you the number of apps deployed vs log-cache memory. 

![image](https://user-images.githubusercontent.com/29627753/92431395-0a282880-f1b5-11ea-9efd-2cd0d39e000f.png)

*Just a note:* Fluentd was consuming an average of 2.5Gi

**Comment by pianohacker** [comment]
This should be fixed in [version 0.5.0](https://github.com/cloudfoundry/cf-k8s-logging/releases/tag/0.5.0).
