### ISSUE TITLE
Enriching logs with Kubernetes labels/annotations via a Fluentd input plugin should be possible with less overhead

### ISSUE THREAD

**Issue by pianohacker** [cloudfoundry/cf-k8s-logging#64]
When enriching Fluentd logs via filtering, I want Kubernetes labels and annotations to be added without dropping performance or adding overhead, so that my log transport infrastructure doesn't overload my cluster.

# AC
Given a Fluentd
When I add the new Fluentd filter plugin
And configure it with my desired labels, annotations, and other necessary information
Then I see my desired labels and annotations on outgoing logs

**Comment by heycait** [comment]
Closing this out as this is an investigation to improving logging performance that was not picked up. This could be re-opened in the future if needed.
